export const pricingPlans = [
  {
    name: "Monthly",
    period: "Month",
    price: "₹299",
    buttonText: "Start Annual Plan",
    features: [
      "Advanced Stock Scanner",
      "Real-Time Market Data",
      "AI-Powered Insights",
      "Advanced Market Analysis",
      "AI-50 NFT events",
      "AI Predictions",
    ],
    popular: false,
  },
  {
    name: "Quarterly",
    period: "Quarter",
    price: "₹855",
    buttonText: "Start Quarterly Plan",
    features: [
      "Advanced Stock Scanner",
      "Real-Time Market Data",
      "AI-Powered Insights",
      "Advanced Market Analysis",
      "AI-50 NFT events",
      "AI Predictions",
    ],
    popular: false,
  },
  {
    name: "Bi-Annual",
    period: "Half Year",
    price: "₹1,710",
    buttonText: "Start Bi-Annual Plan",
    features: [
      "Advanced Stock Scanner",
      "Real-Time Market Data",
      "AI-Powered Insights",
      "Advanced Market Analysis",
      "AI-50 NFT events",
      "AI Predictions",
    ],
    popular: true,
  },
  {
    name: "Annual",
    period: "Year",
    price: "₹3,350",
    buttonText: "Start Annual Plan",
    features: [
      "Advanced Stock Scanner",
      "Real-Time Market Data",
      "AI-Powered Insights",
      "Advanced Market Analysis",
      "AI-50 NFT events",
      "AI Predictions",
    ],
    popular: false,
  },
];
